### ISSUE TITLE
Getting the m3u8 works, but they can't be played

### ISSUE THREAD

**Issue by Numbers11** [Gradleless/vidsrc-bypass#1]
Playing the m3u8 in VLC media player (for example) fails unfortunately. If you try the container m3u8, you get error 403 - but you can prevent that by passing in a browser-like header with embed.su as referrer. However, the video streams that link to the actual file chunks on some shady cdn (for example viper.congacdn.cc) also can't be played, because they give you a "blocked" error message, likely somehow detecting that you don't try to access through the website. Any ideas how to fix this?

**Comment by heyitswit** [comment]
I have some idea, I'll check tonight if I have the time

**Comment by heyitswit** [comment]
Oh sorry I misread what you wrote. There's no way I can fix this. I advise you to use / make a proxy that mediates between the 2 as they do

**Comment by bugbounted** [comment]
@Numbers11 Did you find a solution?
