### ISSUE TITLE
not working can you please explain little bit more

### ISSUE THREAD

**Issue by Gujjugaming2k** [Gradleless/vidsrc-bypass#2]
not working can you please explain little bit more

**Comment by heyitswit** [comment]
How does it “not work” ? Explain, otherwise I can't answer.

**Comment by Gujjugaming2k** [comment]
I have run install comand, after that,

I just run script using node index.ts

Its showing error or package

**Comment by heyitswit** [comment]
Firstly, it's typescript so it'll need to be compiled with node, so just use bun if you don't want to bother with it. And it's a lib, I don't provide a script where you choose your films/series/etc. you need to use the function in your own code

**Comment by Gujjugaming2k** [comment]
we able to extract link

but its not playing on local or online what is the reason ?

https://embed.su/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcN~n1kv1Dlmp5GtKu+zozTUcG8hQC+j~+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFN~lV2p074qshwz3qKJJvkfk2X8cE~87kSzB7Rg=/cGxheWxpc3QubTN1OA==.m3u8

playing this directly on vlc or online m3u8 player 
sample link
  using postman able to fetch m3u8 data as well
  
  
  #EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4500000,RESOLUTION=1920x1080
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcN~n1kv1Dlmp5GtKu+zozTUcG8hQC+j~+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFN~lV2p074qshwz3qKJJvkfk2X8cE~87kSzB7Rg=/MTA4MA==/aW5kZXgubTN1OA==.png
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1800000,RESOLUTION=1280x720
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcN~n1kv1Dlmp5GtKu+zozTUcG8hQC+j~+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFN~lV2p074qshwz3qKJJvkfk2X8cE~87kSzB7Rg=/NzIw/aW5kZXgubTN1OA==.png
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=720000,RESOLUTION=640x360
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcN~n1kv1Dlmp5GtKu+zozTUcG8hQC+j~+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFN~lV2p074qshwz3qKJJvkfk2X8cE~87kSzB7Rg=/MzYw/aW5kZXgubTN1OA==.png

**Comment by heyitswit** [comment]
check issues, there is #1, subject already solved.
