### ISSUE TITLE
extract using embed-su.ts but not able to play that on vlc or online m3u8 player

### ISSUE THREAD

**Issue by Gujjugaming2k** [Gradleless/vidsrc-bypass#4]
we able to extract link

but its not playing on local or online what is the reason ?

https://embed.su/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcN~n1kv1Dlmp5GtKu+zozTUcG8hQC+j~+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFN~lV2p074qshwz3qKJJvkfk2X8cE~87kSzB7Rg=/cGxheWxpc3QubTN1OA==.m3u8

playing this directly on vlc or online m3u8 player
sample link
using postman able to fetch m3u8 data as well

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4500000,RESOLUTION=1920x1080
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcNn1kv1Dlmp5GtKu+zozTUcG8hQC+j+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFNlV2p074qshwz3qKJJvkfk2X8cE87kSzB7Rg=/MTA4MA==/aW5kZXgubTN1OA==.png
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1800000,RESOLUTION=1280x720
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcNn1kv1Dlmp5GtKu+zozTUcG8hQC+j+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFNlV2p074qshwz3qKJJvkfk2X8cE87kSzB7Rg=/NzIw/aW5kZXgubTN1OA==.png
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=720000,RESOLUTION=640x360
/api/proxy/viper/zeltroncloud66.pro/file2/2akfqjg8qNJ+knP7Cc5sWoJvNIK0oqIrVnvPVMLRKlU4n8zmZ3wLV59y2mAEvcNn1kv1Dlmp5GtKu+zozTUcG8hQC+j+3PbPAlVXcWpnBsoyX1KuNw3kynbp5csEWLkn7fFNlV2p074qshwz3qKJJvkfk2X8cE87kSzB7Rg=/MzYw/aW5kZXgubTN1OA==.png

**Comment by heyitswit** [comment]
check issues, there is https://github.com/Gradleless/vidsrc-bypass/issues/1, subject already solved. Please stop spam your message everywhere 😭

**Comment by Numbers11** [comment]
Solution: get an m3u8 proxy like (https://github.com/Eltik/M3U8-Proxy) 
To test: install, run, go to localhost:8080, put your link as Url and 
```
{"referer": "https://embed.su",
"origin": "https://embed.su"}
```
as headers.
