### ISSUE TITLE
vid linkpro no longer working.

### ISSUE THREAD

**Issue by gilbertlucas46** [Gradleless/vidsrc-bypass#8]
It's returning undefined.

I think he's using webassembly?

**Comment by heyitswit** [comment]
Work on my side. They don't use wasm, there's only vidsrc.cc that use wasm actually. Vidlink oftens has SSL handshake error with cloudflare (bad configuration on their side) so it's probably that, just try multiple time or use another provider. 

<img width="832" alt="image" src="https://github.com/user-attachments/assets/9af4a1d8-9a0a-44ba-9560-e9bc698a542d">
